apiVersion: v1
kind: Service
metadata:
  labels:
    component: server
    instance: postgresql
    name: postgresql
  name: anon-a5g-postgresql-lb
  namespace: a5g
spec:
  externalIPs:
    - 10.0.31.206
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp-postgresql
      port: 5432
      protocol: TCP
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/name: postgresql
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}