// autogenerated: do not edit!
// generated from gentemplate [gentemplate -id=temp -d Operation=+ -d Type=int basics/goGenerateDemo/arithmeticFuncs.tmpl]

package main

func Add(x, y int) int {
	return x + y
}
